language: perl
perl:
  - "5.14"

before_install:
  - cpanm Carton

install:
  - carton install

script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" carton exec -- prove -v

after_success:
  - carton exec -- cover -report coveralls